# Email Configuration
mail.smtp.username=simulated
mail.smtp.password=simulated

# Database Configuration (For Windows/Manual setup)
db.host=localhost
db.port=3306
db.name=chuka_voting_db
db.user=root
db.password=
